CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260907144257_InitialCreate') THEN
    CREATE TABLE "Barrios" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nombre" text NOT NULL,
        "Municipio" text NOT NULL,
        "Departamento" text NOT NULL,
        "Pais" text NOT NULL,
        "ZonaTransporte" text NOT NULL,
        CONSTRAINT "PK_Barrios" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260907144257_InitialCreate') THEN
    CREATE TABLE "Clientes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Codigo" text NOT NULL,
        "Tratamiento" text NOT NULL,
        "NombreNegocio" text NOT NULL,
        "RazonSocialExtendida" text NOT NULL,
        "NombreCompleto" text NOT NULL,
        "Nombres" text NOT NULL,
        "Apellidos" text NOT NULL,
        "TipoDocumento" text NOT NULL,
        "NumeroDocumento" text NOT NULL,
        "DigitoVerificacion" integer,
        "Telefono" text,
        "Celular" text,
        "Email" text,
        "EsRural" boolean NOT NULL,
        "DireccionRural" text,
        "ViaTipo" text,
        "ViaNumero" text,
        "ViaLetra" text,
        "ViaCardinalidad" text,
        "CruceNumero" text,
        "PlacaNumero" text,
        "DireccionEstandarizada" text NOT NULL,
        "Barrio" text NOT NULL,
        "Municipio" text NOT NULL,
        "Departamento" text NOT NULL,
        "Pais" text NOT NULL,
        "ZonaTransporte" text,
        "Centro" text NOT NULL,
        "Estrato" integer NOT NULL,
        "ClaseImpuesto" text NOT NULL,
        "CondicionPago" text NOT NULL,
        "Bloqueado" boolean NOT NULL,
        "FechaRetiro" timestamp with time zone,
        "FechaCreacion" timestamp with time zone NOT NULL,
        "FechaModificacion" timestamp with time zone,
        CONSTRAINT "PK_Clientes" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260907144257_InitialCreate') THEN
    CREATE TABLE "ClientesCanalModerno" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TipoDocumento" text NOT NULL,
        "NumeroDocumento" text NOT NULL,
        "NombreCadena" text NOT NULL,
        CONSTRAINT "PK_ClientesCanalModerno" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260907144257_InitialCreate') THEN
    INSERT INTO "Barrios" ("Id", "Departamento", "Municipio", "Nombre", "Pais", "ZonaTransporte")
    VALUES (1, 'Antioquia', 'Medellín', 'Laureles', 'Colombia', 'Zona Centro-Occidente');
    INSERT INTO "Barrios" ("Id", "Departamento", "Municipio", "Nombre", "Pais", "ZonaTransporte")
    VALUES (2, 'Antioquia', 'Medellín', 'El Poblado', 'Colombia', 'Zona Sur-Oriente');
    INSERT INTO "Barrios" ("Id", "Departamento", "Municipio", "Nombre", "Pais", "ZonaTransporte")
    VALUES (3, 'Antioquia', 'Medellín', 'La Floresta', 'Colombia', 'Zona Occidente');
    INSERT INTO "Barrios" ("Id", "Departamento", "Municipio", "Nombre", "Pais", "ZonaTransporte")
    VALUES (4, 'Antioquia', 'Envigado', 'Zúñiga', 'Colombia', 'Zona Sur Aburrá');
    INSERT INTO "Barrios" ("Id", "Departamento", "Municipio", "Nombre", "Pais", "ZonaTransporte")
    VALUES (5, 'Cundinamarca', 'Bogotá D.C.', 'Chapinero', 'Colombia', 'Zona Centro Capital');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260907144257_InitialCreate') THEN
    INSERT INTO "Clientes" ("Id", "Apellidos", "Barrio", "Bloqueado", "Celular", "Centro", "ClaseImpuesto", "Codigo", "CondicionPago", "CruceNumero", "Departamento", "DigitoVerificacion", "DireccionEstandarizada", "DireccionRural", "Email", "EsRural", "Estrato", "FechaCreacion", "FechaModificacion", "FechaRetiro", "Municipio", "NombreCompleto", "NombreNegocio", "Nombres", "NumeroDocumento", "Pais", "PlacaNumero", "RazonSocialExtendida", "Telefono", "TipoDocumento", "Tratamiento", "ViaCardinalidad", "ViaLetra", "ViaNumero", "ViaTipo", "ZonaTransporte")
    VALUES (1, 'Pérez, Gómez', 'Laureles', FALSE, NULL, 'Sede Principal Medellín', 'Persona Natural', 'CLI-00482', '0010 Contado', '5', 'Antioquia', NULL, 'Calle 10A Sur # 5-30', NULL, 'jc.perez@distribucionesjc.co', FALSE, 5, TIMESTAMPTZ '2026-01-15T10:00:00Z', NULL, NULL, 'Medellín', 'Juan Carlos Pérez Gómez', 'Distribuciones JC', 'Juan, Carlos', '1020485921', 'Colombia', '30', 'Juan Carlos Pérez Gómez', '312 456 7890', 'C.C.', 'Sr/Sra', 'Sur', 'A', '10', 'Calle', 'Zona Centro-Occidente');
    INSERT INTO "Clientes" ("Id", "Apellidos", "Barrio", "Bloqueado", "Celular", "Centro", "ClaseImpuesto", "Codigo", "CondicionPago", "CruceNumero", "Departamento", "DigitoVerificacion", "DireccionEstandarizada", "DireccionRural", "Email", "EsRural", "Estrato", "FechaCreacion", "FechaModificacion", "FechaRetiro", "Municipio", "NombreCompleto", "NombreNegocio", "Nombres", "NumeroDocumento", "Pais", "PlacaNumero", "RazonSocialExtendida", "Telefono", "TipoDocumento", "Tratamiento", "ViaCardinalidad", "ViaLetra", "ViaNumero", "ViaTipo", "ZonaTransporte")
    VALUES (2, 'Helena, Restrepo', 'Zúñiga', FALSE, NULL, 'Sede Sur Envigado', 'Persona Natural', 'CLI-00319', '0010 Contado', NULL, 'Antioquia', NULL, 'Carrera 43A # 25-10', NULL, 'mrestrepo@alamosres.org', FALSE, 4, TIMESTAMPTZ '2026-01-18T14:30:00Z', NULL, NULL, 'Envigado', 'María Helena Restrepo', 'Residencial Los Álamos', 'María', '43892115', 'Colombia', NULL, 'María Helena Restrepo', '300 289 1144', 'C.C.', 'Sr/Sra', NULL, NULL, NULL, NULL, 'Zona Sur Aburrá');
    INSERT INTO "Clientes" ("Id", "Apellidos", "Barrio", "Bloqueado", "Celular", "Centro", "ClaseImpuesto", "Codigo", "CondicionPago", "CruceNumero", "Departamento", "DigitoVerificacion", "DireccionEstandarizada", "DireccionRural", "Email", "EsRural", "Estrato", "FechaCreacion", "FechaModificacion", "FechaRetiro", "Municipio", "NombreCompleto", "NombreNegocio", "Nombres", "NumeroDocumento", "Pais", "PlacaNumero", "RazonSocialExtendida", "Telefono", "TipoDocumento", "Tratamiento", "ViaCardinalidad", "ViaLetra", "ViaNumero", "ViaTipo", "ZonaTransporte")
    VALUES (3, 'Inversiones Morales S.A.S.', 'Laureles', FALSE, NULL, 'Sede Principal Medellín', 'Persona Jurídica', 'CLI-00754', '0010 Contado', NULL, 'Antioquia', 3, 'Calle 75 Sur # 45-20', NULL, 'gerencia@morales.co', FALSE, 3, TIMESTAMPTZ '2026-02-01T09:15:00Z', NULL, NULL, 'Medellín', 'Inversiones Morales S.A.S.', 'Inversiones Morales S.A.S.', 'Inversiones Morales S.A.S.', '901442809', 'Colombia', NULL, 'Inversiones Morales S.A.S.', '317 890 2311', 'NIT', 'Empresa', NULL, NULL, NULL, NULL, 'Zona Centro-Occidente');
    INSERT INTO "Clientes" ("Id", "Apellidos", "Barrio", "Bloqueado", "Celular", "Centro", "ClaseImpuesto", "Codigo", "CondicionPago", "CruceNumero", "Departamento", "DigitoVerificacion", "DireccionEstandarizada", "DireccionRural", "Email", "EsRural", "Estrato", "FechaCreacion", "FechaModificacion", "FechaRetiro", "Municipio", "NombreCompleto", "NombreNegocio", "Nombres", "NumeroDocumento", "Pais", "PlacaNumero", "RazonSocialExtendida", "Telefono", "TipoDocumento", "Tratamiento", "ViaCardinalidad", "ViaLetra", "ViaNumero", "ViaTipo", "ZonaTransporte")
    VALUES (4, 'Echeverri, Salazar', 'La Floresta', TRUE, NULL, 'Sede Norte Bello', 'Persona Natural', 'CLI-00891', '0010 Contado', NULL, 'Antioquia', NULL, 'Diagonal 50 # 32-15', NULL, 'camilareal@urbanportal.co', FALSE, 3, TIMESTAMPTZ '2026-01-10T08:00:00Z', NULL, TIMESTAMPTZ '2026-02-20T16:00:00Z', 'Medellín', 'Camila Echeverri Salazar', 'Urbanización Portal Real', 'Camila', '1017332901', 'Colombia', NULL, 'Camila Echeverri Salazar', '315 771 0088', 'C.C.', 'Sr/Sra', NULL, NULL, NULL, NULL, 'Zona Occidente');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260907144257_InitialCreate') THEN
    INSERT INTO "ClientesCanalModerno" ("Id", "NombreCadena", "NumeroDocumento", "TipoDocumento")
    VALUES (1, 'Éxito Poblado', '12345678', 'C.C.');
    INSERT INTO "ClientesCanalModerno" ("Id", "NombreCadena", "NumeroDocumento", "TipoDocumento")
    VALUES (2, 'Jumbo Las Vegas', '900111222', 'NIT');
    INSERT INTO "ClientesCanalModerno" ("Id", "NombreCadena", "NumeroDocumento", "TipoDocumento")
    VALUES (3, 'Olímpica Calle 10', '800123456', 'NIT');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260907144257_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Clientes_Codigo" ON "Clientes" ("Codigo");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260907144257_InitialCreate') THEN
    CREATE INDEX "IX_Clientes_NumeroDocumento" ON "Clientes" ("NumeroDocumento");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260907144257_InitialCreate') THEN
    PERFORM setval(
        pg_get_serial_sequence('"Barrios"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Barrios") + 1,
            nextval(pg_get_serial_sequence('"Barrios"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"Clientes"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Clientes") + 1,
            nextval(pg_get_serial_sequence('"Clientes"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"ClientesCanalModerno"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "ClientesCanalModerno") + 1,
            nextval(pg_get_serial_sequence('"ClientesCanalModerno"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260907144257_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260907144257_InitialCreate', '8.0.11');
    END IF;
END $EF$;
COMMIT;

