// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260907144257_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.BarrioCatalogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZonaTransporte")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Barrios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Departamento = "Antioquia",
                            Municipio = "Medellín",
                            Nombre = "Laureles",
                            Pais = "Colombia",
                            ZonaTransporte = "Zona Centro-Occidente"
                        },
                        new
                        {
                            Id = 2,
                            Departamento = "Antioquia",
                            Municipio = "Medellín",
                            Nombre = "El Poblado",
                            Pais = "Colombia",
                            ZonaTransporte = "Zona Sur-Oriente"
                        },
                        new
                        {
                            Id = 3,
                            Departamento = "Antioquia",
                            Municipio = "Medellín",
                            Nombre = "La Floresta",
                            Pais = "Colombia",
                            ZonaTransporte = "Zona Occidente"
                        },
                        new
                        {
                            Id = 4,
                            Departamento = "Antioquia",
                            Municipio = "Envigado",
                            Nombre = "Zúñiga",
                            Pais = "Colombia",
                            ZonaTransporte = "Zona Sur Aburrá"
                        },
                        new
                        {
                            Id = 5,
                            Departamento = "Cundinamarca",
                            Municipio = "Bogotá D.C.",
                            Nombre = "Chapinero",
                            Pais = "Colombia",
                            ZonaTransporte = "Zona Centro Capital"
                        });
                });

            modelBuilder.Entity("backend.Models.ClienteCanalModerno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreCadena")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ClientesCanalModerno");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NombreCadena = "Éxito Poblado",
                            NumeroDocumento = "12345678",
                            TipoDocumento = "C.C."
                        },
                        new
                        {
                            Id = 2,
                            NombreCadena = "Jumbo Las Vegas",
                            NumeroDocumento = "900111222",
                            TipoDocumento = "NIT"
                        },
                        new
                        {
                            Id = 3,
                            NombreCadena = "Olímpica Calle 10",
                            NumeroDocumento = "800123456",
                            TipoDocumento = "NIT"
                        });
                });

            modelBuilder.Entity("backend.Models.ClienteResidencial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Barrio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Bloqueado")
                        .HasColumnType("boolean");

                    b.Property<string>("Celular")
                        .HasColumnType("text");

                    b.Property<string>("Centro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClaseImpuesto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CondicionPago")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CruceNumero")
                        .HasColumnType("text");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DigitoVerificacion")
                        .HasColumnType("integer");

                    b.Property<string>("DireccionEstandarizada")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DireccionRural")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EsRural")
                        .HasColumnType("boolean");

                    b.Property<int>("Estrato")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaRetiro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreNegocio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlacaNumero")
                        .HasColumnType("text");

                    b.Property<string>("RazonSocialExtendida")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tratamiento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ViaCardinalidad")
                        .HasColumnType("text");

                    b.Property<string>("ViaLetra")
                        .HasColumnType("text");

                    b.Property<string>("ViaNumero")
                        .HasColumnType("text");

                    b.Property<string>("ViaTipo")
                        .HasColumnType("text");

                    b.Property<string>("ZonaTransporte")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("NumeroDocumento");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellidos = "Pérez, Gómez",
                            Barrio = "Laureles",
                            Bloqueado = false,
                            Centro = "Sede Principal Medellín",
                            ClaseImpuesto = "Persona Natural",
                            Codigo = "CLI-00482",
                            CondicionPago = "0010 Contado",
                            CruceNumero = "5",
                            Departamento = "Antioquia",
                            DireccionEstandarizada = "Calle 10A Sur # 5-30",
                            Email = "jc.perez@distribucionesjc.co",
                            EsRural = false,
                            Estrato = 5,
                            FechaCreacion = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Municipio = "Medellín",
                            NombreCompleto = "Juan Carlos Pérez Gómez",
                            NombreNegocio = "Distribuciones JC",
                            Nombres = "Juan, Carlos",
                            NumeroDocumento = "1020485921",
                            Pais = "Colombia",
                            PlacaNumero = "30",
                            RazonSocialExtendida = "Juan Carlos Pérez Gómez",
                            Telefono = "312 456 7890",
                            TipoDocumento = "C.C.",
                            Tratamiento = "Sr/Sra",
                            ViaCardinalidad = "Sur",
                            ViaLetra = "A",
                            ViaNumero = "10",
                            ViaTipo = "Calle",
                            ZonaTransporte = "Zona Centro-Occidente"
                        },
                        new
                        {
                            Id = 2,
                            Apellidos = "Helena, Restrepo",
                            Barrio = "Zúñiga",
                            Bloqueado = false,
                            Centro = "Sede Sur Envigado",
                            ClaseImpuesto = "Persona Natural",
                            Codigo = "CLI-00319",
                            CondicionPago = "0010 Contado",
                            Departamento = "Antioquia",
                            DireccionEstandarizada = "Carrera 43A # 25-10",
                            Email = "mrestrepo@alamosres.org",
                            EsRural = false,
                            Estrato = 4,
                            FechaCreacion = new DateTime(2026, 1, 18, 14, 30, 0, 0, DateTimeKind.Utc),
                            Municipio = "Envigado",
                            NombreCompleto = "María Helena Restrepo",
                            NombreNegocio = "Residencial Los Álamos",
                            Nombres = "María",
                            NumeroDocumento = "43892115",
                            Pais = "Colombia",
                            RazonSocialExtendida = "María Helena Restrepo",
                            Telefono = "300 289 1144",
                            TipoDocumento = "C.C.",
                            Tratamiento = "Sr/Sra",
                            ZonaTransporte = "Zona Sur Aburrá"
                        },
                        new
                        {
                            Id = 3,
                            Apellidos = "Inversiones Morales S.A.S.",
                            Barrio = "Laureles",
                            Bloqueado = false,
                            Centro = "Sede Principal Medellín",
                            ClaseImpuesto = "Persona Jurídica",
                            Codigo = "CLI-00754",
                            CondicionPago = "0010 Contado",
                            Departamento = "Antioquia",
                            DigitoVerificacion = 3,
                            DireccionEstandarizada = "Calle 75 Sur # 45-20",
                            Email = "gerencia@morales.co",
                            EsRural = false,
                            Estrato = 3,
                            FechaCreacion = new DateTime(2026, 2, 1, 9, 15, 0, 0, DateTimeKind.Utc),
                            Municipio = "Medellín",
                            NombreCompleto = "Inversiones Morales S.A.S.",
                            NombreNegocio = "Inversiones Morales S.A.S.",
                            Nombres = "Inversiones Morales S.A.S.",
                            NumeroDocumento = "901442809",
                            Pais = "Colombia",
                            RazonSocialExtendida = "Inversiones Morales S.A.S.",
                            Telefono = "317 890 2311",
                            TipoDocumento = "NIT",
                            Tratamiento = "Empresa",
                            ZonaTransporte = "Zona Centro-Occidente"
                        },
                        new
                        {
                            Id = 4,
                            Apellidos = "Echeverri, Salazar",
                            Barrio = "La Floresta",
                            Bloqueado = true,
                            Centro = "Sede Norte Bello",
                            ClaseImpuesto = "Persona Natural",
                            Codigo = "CLI-00891",
                            CondicionPago = "0010 Contado",
                            Departamento = "Antioquia",
                            DireccionEstandarizada = "Diagonal 50 # 32-15",
                            Email = "camilareal@urbanportal.co",
                            EsRural = false,
                            Estrato = 3,
                            FechaCreacion = new DateTime(2026, 1, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            FechaRetiro = new DateTime(2026, 2, 20, 16, 0, 0, 0, DateTimeKind.Utc),
                            Municipio = "Medellín",
                            NombreCompleto = "Camila Echeverri Salazar",
                            NombreNegocio = "Urbanización Portal Real",
                            Nombres = "Camila",
                            NumeroDocumento = "1017332901",
                            Pais = "Colombia",
                            RazonSocialExtendida = "Camila Echeverri Salazar",
                            Telefono = "315 771 0088",
                            TipoDocumento = "C.C.",
                            Tratamiento = "Sr/Sra",
                            ZonaTransporte = "Zona Occidente"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
